version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: blog-db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: blog-app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: password

volumes:
  db_data:
